import FormData from 'form-data';
export const config={api:{bodyParser:{sizeLimit:'12mb'}}};
const prompts={
deer:`Edit this kindergarten drawing into a coherent warm children's picture-book illustration. IMPORTANT: do NOT preserve the child's crude raw strokes as crude strokes. First infer what each child-drawn mark is intended to represent, then REDRAW it as a polished, recognizable storybook element. Preserve the child's idea, approximate location, number, relative size, direction, and main colors. For example, simple tree marks should become full leafy trees; colored dots may become flowers; green strokes may become grass or plants. Completely remove ALL construction machinery, barriers, cut stumps, damaged trunks, branch piles, barren excavated ground, and development elements. Replace those damaged areas with a continuous healthy habitat guided primarily by the child's additions. Keep the roe deer recognizable and in the same general position, but make it clearly joyful and relaxed. Keep the original landscape composition and wide framing as closely as possible. No text, labels, borders, or captions.`,
bear:`Edit this kindergarten drawing into a coherent warm children's picture-book illustration. IMPORTANT: do NOT preserve the child's crude raw strokes as crude strokes. First infer what the child intended to make to protect the Asiatic black bear, then REDRAW those marks as polished, recognizable protective storybook elements. Preserve the child's core idea, approximate location, number, relative size, direction, and main colors. Example: a rough fence-like scribble must become a well-formed attractive protective fence in roughly the same place; tree-like marks become full trees; a sign-like mark becomes a clear animal-protection sign without written text. Follow the child's actual idea rather than forcing every drawing into a fence. Completely remove the threatening person, capture net, capture cage, traps, and ALL hunting/capture equipment. Do not add police, arrest, weapons, punishment, violence, or confrontation. Keep the Asiatic black bear recognizable, including its pale crescent chest marking and same general position, but make it clearly happy, relaxed, and safe. Keep the original landscape composition and wide framing as closely as possible. The final result must look like a finished children's picture-book scene, not a photo with a child's scribbles left on top. No text, labels, borders, or captions.`
};
export default async function handler(req,res){
if(req.method!=='POST')return res.status(405).json({error:'POST 요청만 가능합니다.'});
const apiKey=process.env.OPENAI_API_KEY;if(!apiKey)return res.status(500).json({error:'OPENAI_API_KEY가 설정되지 않았습니다.'});
try{
const {image,mission='deer'}=req.body||{};if(!image||typeof image!=='string')return res.status(400).json({error:'그림 이미지가 없습니다.'});if(!prompts[mission])return res.status(400).json({error:'알 수 없는 미션입니다.'});
const match=image.match(/^data:image\/(png|jpeg|jpg|webp);base64,(.+)$/);if(!match)return res.status(400).json({error:'이미지 형식이 올바르지 않습니다.'});
const subtype=match[1]==='jpg'?'jpeg':match[1],mime=`image/${subtype}`,ext=subtype==='jpeg'?'jpg':subtype,bytes=Buffer.from(match[2],'base64');
const form=new FormData();form.append('model','gpt-image-2');form.append('image',bytes,{filename:`child-drawing.${ext}`,contentType:mime,knownLength:bytes.length});form.append('prompt',prompts[mission]);form.append('size','1536x1024');
const response=await fetch('https://api.openai.com/v1/images/edits',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,...form.getHeaders()},body:form.getBuffer()});
const text=await response.text();let data;try{data=JSON.parse(text)}catch{data={raw:text}}
if(!response.ok)return res.status(response.status).json({error:data?.error?.message||`OpenAI API 오류 (${response.status})`});
const b64=data?.data?.[0]?.b64_json,url=data?.data?.[0]?.url;if(b64)return res.status(200).json({image:`data:image/png;base64,${b64}`});if(url)return res.status(200).json({image:url});
return res.status(502).json({error:'AI 이미지 응답을 찾지 못했습니다.'});
}catch(err){console.error(err);return res.status(500).json({error:err?.message||'서버 오류가 발생했습니다.'})}}
