import FormData from 'form-data';
export const config={api:{bodyParser:{sizeLimit:'12mb'}}};
const prompts={
deer:`This image shows a kindergarten child's drawing added over a storybook scene of a sad roe deer in a deforested habitat. Re-illustrate the CHILD'S DRAWN MARKS into polished storybook elements while preserving the child's core ideas, approximate position, number, relative size, and main colors. Transform simple marks into natural trees, flowers, grass, or habitat features according to what the child appears to intend. Completely remove construction-site elements, machinery, barriers, cut stumps, damaged trunks, branches, and barren excavated ground, replacing them with a healthy continuous forest guided by the child's additions. Keep the roe deer recognizable and in the same general position, but make it clearly joyful because its forest has returned. Warm coherent children's picture-book style. No text, letters, labels, borders, or captions.`,
bear:`This image shows a kindergarten child's drawing added over a children's storybook scene of a frightened Asiatic black bear (moon bear) threatened by a person carrying a capture net and an empty capture cage. Re-illustrate the CHILD'S DRAWN MARKS rather than preserving their crude line style. Infer what the child intended, then transform those marks into polished picture-book elements that help PROTECT the bear. Preserve the child's core ideas, approximate position, number, relative size, and main colors. A line or barrier may become a protective boundary; tree-like marks may become protective forest; a sign-like shape may become an animal-protection sign; other marks should be interpreted according to the child's visual idea. Do not force every child into the same solution. IMPORTANT: completely remove the threatening person, capture net, capture cage, traps, and all capture or hunting equipment from the final image. Do not show police, punishment, arrest, weapons, violence, or confrontation. Focus on the positive result: the bear is safe because of the child's idea. Keep the Asiatic black bear recognizable with its pale crescent chest marking and same general position, but make it clearly happy, relaxed, and safe. Integrate the child's transformed protective idea naturally into the forest. Warm coherent children's picture-book style. No text, letters, labels, borders, or captions.`
};
export default async function handler(req,res){
if(req.method!=='POST')return res.status(405).json({error:'POST 요청만 가능합니다.'});
const apiKey=process.env.OPENAI_API_KEY;if(!apiKey)return res.status(500).json({error:'OPENAI_API_KEY가 설정되지 않았습니다.'});
try{
const {image,mission='deer'}=req.body||{};if(!image||typeof image!=='string')return res.status(400).json({error:'그림 이미지가 없습니다.'});if(!prompts[mission])return res.status(400).json({error:'알 수 없는 미션입니다.'});
const match=image.match(/^data:image\/(png|jpeg|jpg|webp);base64,(.+)$/);if(!match)return res.status(400).json({error:'이미지 형식이 올바르지 않습니다.'});
const subtype=match[1]==='jpg'?'jpeg':match[1],mime=`image/${subtype}`,ext=subtype==='jpeg'?'jpg':subtype,bytes=Buffer.from(match[2],'base64');
const form=new FormData();form.append('model','gpt-image-2');form.append('image',bytes,{filename:`child-drawing.${ext}`,contentType:mime,knownLength:bytes.length});form.append('prompt',prompts[mission]);form.append('size','1536x1024');
const response=await fetch('https://api.openai.com/v1/images/edits',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,...form.getHeaders()},body:form.getBuffer()});
const text=await response.text();let data;try{data=JSON.parse(text)}catch{data={raw:text}}
if(!response.ok)return res.status(response.status).json({error:data?.error?.message||`OpenAI API 오류 (${response.status})`});
const b64=data?.data?.[0]?.b64_json,url=data?.data?.[0]?.url;if(b64)return res.status(200).json({image:`data:image/png;base64,${b64}`});if(url)return res.status(200).json({image:url});
return res.status(502).json({error:'AI 이미지 응답을 찾지 못했습니다.'});
}catch(err){console.error(err);return res.status(500).json({error:err?.message||'서버 오류가 발생했습니다.'})}}
